### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by rasouliali1379** [rekabhq/fantom#18]
`Null check operator used on a null value
    #0      ResponseClassGenerator.generateResponse.<anonymous closure> 
   (package:fantom/src/generator/response/response_class_generator.dart:41:45)
#1      MapMixin.map (dart:collection/maps.dart:170:28)
#2      ResponseClassGenerator.generateResponse (package:fantom/src/generator/response/response_class_generator.dart:38:68)
#3      ResponseClassGenerator.generateResponses.<anonymous closure> (package:fantom/src/generator/response/response_class_generator.dart:89:29)
#4      MapMixin.map (dart:collection/maps.dart:170:28)
#5      ResponseClassGenerator.generateResponses (package:fantom/src/generator/response/response_class_generator.dart:81:71)
#6      MethodResponseParser.parseResponses (package:fantom/src/generator/api/method/response_parser.dart:15:55)
#7      ApiMethodGenerator._generateOperation (package:fantom/src/generator/api/method/api_method_generator.dart:117:63)
#8      ApiMethodGenerator.generateMethods (package:fantom/src/generator/api/method/api_method_generator.dart:79:11)
#9      ApiSubClassGenerator._generateApiMethods (package:fantom/src/generator/api/sub_class/api_sub_class_generator.dart:66:26)
#10     ApiSubClassGenerator._generateFileContent (package:fantom/src/generator/api/sub_class/api_sub_class_generator.dart:35:17)
#11     ApiSubClassGenerator.generate (package:fantom/src/generator/api/sub_class/api_sub_class_generator.dart:18:25)
#12     ApiClassGenerator._generateApiClasses (package:fantom/src/generator/api/class/api_class_generator.dart:33:45)
#13     ApiClassGenerator.generate (package:fantom/src/generator/api/class/api_class_generator.dart:20:24)
#14     Generator.generate (package:fantom/src/generator/generator.dart:67:45)
#15     GenerateCommand.runCommand (package:fantom/src/cli/commands/generate.dart:165:10)
#16     BaseCommand.run (package:fantom/src/cli/commands/base_command.dart:38:12)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#18     FantomCli.run (package:fantom/src/cli/fantom_cli.dart:38:22)
<asynchronous suspension>
#19     main (file:///Users/samrd/Dev/Dart/Projects/fantom/bin/main.dart:6:18)
<asynchronous suspension>`

**Comment by payam-zahedi** [comment]
@easazade @FatulM 
we should check out this.

**Comment by easazade** [comment]
hi @rasouliali1379 . can you provide the `openapi` file so we can reproduce this error

**Comment by easazade** [comment]
@rasouliali1379  Closing this since there is no response. feel free to reopen this

**Comment by easazade** [comment]
@rasouliali1379  Closing this since there is no data to check the reported issue. feel free to reopen this

**Comment by rasouliali1379** [comment]
@easazade close it, I don't care 😅
